stages:
  preprocess:
    cmd: python model/preprocess.py --input ${data.raw_path} --output_train ${data.processed_train_path} --output_val ${data.processed_val_path}
    deps:
      - model/preprocess.py
    outs:
      - ${data.processed_train_path}
      - ${data.processed_val_path}
  train:
    cmd: python model/train.py
    deps:
      - model/train.py
      - ${data.processed_train_path}
    outs:
      - models/model.pkl
  evaluate:
    cmd: python model/evaluate.py
    deps:
      - ${data.processed_val_path}
      - model/evaluate.py
      - models/model.pkl